language: android
jdk: oraclejdk8
env:
  global:
    - EMULATOR_API_LEVEL=22
  matrix:
    - ANDROID_SDKS=android-23,sysimg-23 ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23
    - android-$EMULATOR_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19
    - extra-android-m2repository # Design Support Library
    - extra-google-m2repository # Google cast

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    # - sys-img-x86-android-17

before_install:
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
  - ./imgurbash.sh screen.png

script:
    - gradle build connectedCheck
